### ISSUE TITLE
dragon set is suddenly breakable????

### ISSUE THREAD

**Issue by spaghettilmfao** [kwpugh/Gobber_mod_fabric#11]
minecraft 1.20.6, gobber 2.9.39, lucky tnt mod 5.0, mining dimensions 1.6.31 (if that helps)
i have this tnt mod installed, and i set off a tnt x20000 in the hunting dimension and lagged my computer for 20 minutes basically, and when i respawned in the overworld, my dragon set suddenly had durability loss and no longer says unbreakable at the bottom. the armor had some enchants, but they were all vanilla enchants. what the heck happened?

**Comment by kwpugh** [comment]
I'm guessing you lost the original armor due to the extreme lag and the game gave you a non-crafted by player version the of the armor.   No idea why.
