### ISSUE TITLE
[1.21] Looting doesnt seem to work on Gobber Swords

### ISSUE THREAD

**Issue by xKamiyda156** [kwpugh/Gobber_mod_fabric#12]
Hello,

i noticed that on my Server with Gobber2 installed, the looting enchant doesnt seem to work on the Gobber swords.

I Tried upgrading the version, but that didnt help and i tried looking in the config file for it, but didnt seem to find anything in that direction.

**Comment by kwpugh** [comment]
which version of Gobber are you running?

**Comment by xKamiyda156** [comment]
Gobber2-Fabric-1.21-2.10.20 before that i used the Gobber2-Fabric-1.21-2.10.18 version, but i just replaced the mod in the mods folder, maybe i need to do something else aswell?

**Comment by xKamiyda156** [comment]
Im also running the mod MoreGems which also adds some enchantments maybe that could be an issue too?

**Comment by kwpugh** [comment]
what enchants are on the sword in question and from which mods?

I tested just looting and it works fine in my setup

**Comment by kwpugh** [comment]
Also, post a log so I can see what other mods you are running and if there are any errors

**Comment by xKamiyda156** [comment]
These are the enchants on my Sword 
-Sharpness | Standard MC
-Sweeping Edge | Standard MC
-Looting | Standard MC
-Unbreaking | Standard MC
-Mending |  Standard MC
-SmithBlade | Gobber
-Experience Boost | Gobber
-Mercy Kill | More Gems (Passive Animals die one shot (might be this one if i think about it))
-Blessing | Gobber
-Razor Sharpness | MoreGems (Adds to the Attack DMG)
-Quickening | MoreGems (Adds boost of power to your attack)
-Wisdom | MoreGems (Recieve more XP)

![Bild_2024-07-16_143054399](https://github.com/user-attachments/assets/e1b524ea-c122-4907-b3e4-d06c5ff26edd)

Log is that one idk if its the right one:
[latest.log](https://github.com/user-attachments/files/16248911/latest.log)

**Comment by kwpugh** [comment]
What test are you performing to determine that you are NOT getting Looting?

**Comment by kwpugh** [comment]
Mercy Kill just deals 100 damage to the animal struck, so I don't think that would affect looting since the animal is killed by the player.

**Comment by xKamiyda156** [comment]
Killing multiple Mobs and always getting the „normal“ Minecraft drop rates without looting as i remember them and I tried getting a wither skeleton head with the sword and in around 100 kills there wasn’t a single head drop, I know it’s rng after all but it was never that rare when I played vanilla before. 

I can record a video tomorrow if u want

**Comment by kwpugh** [comment]
Ok, I did some controlled test with a similar enchanted sword.
![Screenshot 2024-07-16 at 9 05 53 PM](https://github.com/user-attachments/assets/cd1eea3e-d49d-488f-98b6-8cca92689a06)

I used an enchanted sword and and unenchanted sword, each killing 10 Pigln
![Screenshot 2024-07-16 at 9 05 00 PM](https://github.com/user-attachments/assets/507c5514-2c0b-4b68-8b08-13d83dbf3b31)

Looting is boosting the amount of drops

also, Looting has no affect on the chance of dropping a skull from a wither skeleton.

BTW: the Nether Sword improves on that last point.

**Comment by kwpugh** [comment]
I tried a diamond sword with Looting 3 for comparison.  It did a little better, but that could be just a matter of chance.
![Screenshot 2024-07-16 at 9 13 20 PM](https://github.com/user-attachments/assets/ec3d4732-89de-47c1-9f8d-2f7b23df4431)

**Comment by kwpugh** [comment]
Interestingly, there is a difference with Looting and passive animals (which is affected by Mercy Kill)
Top 2 rows are drops for 10 cows with crazy enchanted sword like your
Next 2 rows are end sword with Lotting 3 only
bottom line is diamond sword with looting 3
![Screenshot 2024-07-16 at 9 35 37 PM](https://github.com/user-attachments/assets/2498e3ee-3c66-4510-add7-e9f978d85197)

A noticeable difference.  Perhaps looting is affected by the overkill damage of the Mercy Kill.

**Comment by kwpugh** [comment]
Ahh, good call on suggesting Mercy Kill.  I was inflicting damage of `generic` rather than `playerAttack`.

Top 2 rows are from crazy enchanted on 10 cows
Next 2 are just Looting 3
Bottom line is diamond with Looting 3

Looks like the crazy enchanted sword performs as one would expect with Looting 3
![Screenshot 2024-07-16 at 9 48 41 PM](https://github.com/user-attachments/assets/21a5ee8e-1931-453d-bc7b-168fc033b542)

I will push out an update with the fix

Thanks for reporting.

**Comment by xKamiyda156** [comment]
I was just writing a big answer as I got the email so I’ll just deleted it and keep it short :D

no problem at first I thought maybe I was just trippin or something but I played that much mc that I felt something was off

No Problem, glad I could somewhat help :D

have a nice day/evening/night

**Comment by kwpugh** [comment]
I pushed a curseforge update MoreGems 1.7.12 that will fix the issue.
