### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by idenher1o** [kwpugh/Gobber_mod_fabric#13]
Where and how do i get the enchantments that are added in this mod? Theyre nowhere.

**Comment by kwpugh** [comment]
you can get them in the enchanting table, via villager trades and in various random treasure throughout the worlds.

**Comment by idenher1o** [comment]
are some rarer than others? ive only seen 1 gobber enchantment and ive played on this save for a while

**Comment by kwpugh** [comment]
Most of the gobber enchantments are rare or very rare.

**Comment by idenher1o** [comment]
Thanks. Incredible mod btw i cant play without it
