### ISSUE TITLE
Non-fully items (Fabric 1.21)

### ISSUE THREAD

**Issue by VamenSol1dnik** [kwpugh/Gobber_mod_fabric#14]
I have version 2.10.21 and i haven`t any blocks and items (for example, ring for animals or blocks with area against aggressive mobs)
![image](https://github.com/user-attachments/assets/0721bd74-2b42-44fc-994a-fd553f00119c)
![image](https://github.com/user-attachments/assets/775369a4-6155-41a3-8bf4-db2817b60ed8)

**Comment by kwpugh** [comment]
That was in older versions of the mod.

ring for animals and the area effect blocks are not part of the mob.

Check out Ward Blocks mod for those blocks.

**Comment by VamenSol1dnik** [comment]
So, in new version they are absent? And will work a few rings in inventory, if they are in shulkerbox? Not needed all medalions and rings, just part (1/3 or 1/2)


And i noticed, that medallions of healing, especially healing3, don`t working (or extreemly slow)
And, ring of repair can`t repair, for example, Tanzanite pixaxe from Enriched.

**Comment by kwpugh** [comment]
I just checked the healing medallions and they work fine.  Keep in mind if you are using any performance enhancement mods, items that rely on ticking the player inventory might be affected since they reduce the amount of player ticks.

Checking the repair now.

**Comment by kwpugh** [comment]
none of the rings or medallions will work in a shulkerbox, only inventory or enderchest (if enabled in config).

I tried the Enriched tanzanite shovel and the ring of repair works fine on it.  Again, you likely have a mod that is reducing player tick which the ring of repair utilizes.

**Comment by VamenSol1dnik** [comment]
Maybe, cause of 2 mods of rings?
![image](https://github.com/user-attachments/assets/f685b8e0-e4b3-4fe3-9a4d-028532f67de3)

**Comment by kwpugh** [comment]
What do you mean?

**Comment by VamenSol1dnik** [comment]
rings, separate from main mode

**Comment by VamenSol1dnik** [comment]
How to find this mod?

**Comment by kwpugh** [comment]
All my mods are available here: https://www.curseforge.com/members/kwpugh/projects

**Comment by VamenSol1dnik** [comment]
i am about mod with ticks which prevents to working items

**Comment by kwpugh** [comment]
oh, are running a modpack or your own selection?

**Comment by VamenSol1dnik** [comment]
own selection

**Comment by kwpugh** [comment]
did you add any mods that improve performance?

**Comment by VamenSol1dnik** [comment]
Only Sodium

**Comment by kwpugh** [comment]
then try without Sodium

**Comment by VamenSol1dnik** [comment]
Oh, can be also https://modrinth.com/mod/modernfix?

**Comment by VamenSol1dnik** [comment]
Oops, is there some OP? 
![image](https://github.com/user-attachments/assets/f4c4ed94-4caa-4064-bf88-8b2a49a92984)

(End unbreakable items from Random Ore have durability, is this normal?)

**Comment by kwpugh** [comment]
End tools are only unbreakable if they are crafted by player.  if they are received by creative or loot, they are not.

**Comment by VamenSol1dnik** [comment]
Okay, this is so balanced)

**Comment by kwpugh** [comment]
Also, regarding the ring of repair.  Keep in mind that it only repairs one item at a time and will skip the item in the player's main hand.

**Comment by VamenSol1dnik** [comment]
I know, i have 283 Days in my world.
Also, what kind items can be added soon?

**Comment by kwpugh** [comment]
what do you mean?

If you have questions, please come to the Discord channel:  https://discord.gg/EXCwbNuQX2

The issue log is for issues.

**Comment by VamenSol1dnik** [comment]
About languages, not all items can be translated

**Comment by kwpugh** [comment]
yeah, lang files may not be up-to-date

I only know English

**Comment by VamenSol1dnik** [comment]
![image](https://github.com/user-attachments/assets/79981117-ee23-44ab-a33e-6c0afdbbb78e)
i dont understand, how it works? in red font

**Comment by kwpugh** [comment]
in red, that is the area of effect, 11 blocks horizontal by 4 blocks vertical

**Comment by kwpugh** [comment]
right-click ring no drops from blocks
sneak + right-click you get drops from blocks

**Comment by VamenSol1dnik** [comment]
> right-click ring no drops from blocks sneak + right-click you get drops from blocks

**Comment by VamenSol1dnik** [comment]
i dont use issues so often, so i wanted to say that i know. I asked only for red

**Comment by kwpugh** [comment]
I'm not going to carry on a conversation in the issue log.

If you have non-issue questions, please use the Discord.

**Comment by VamenSol1dnik** [comment]
I cannot join to discord cause of that issue
![image](https://github.com/user-attachments/assets/705a66f0-6cce-4428-a0e6-b77d73b1fd5c)

**Comment by kwpugh** [comment]
Cannot replicate on my end.  Any other questions should be directed to the support Discord.
